### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by edurocks** [mockito/mockito-kotlin#438]
Good Afternoon, 
When I try to compile my project with the dependency it gives me the following error: 

Could not download mockito-kotlin-2.2.0.jar (com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0)
      > Could not get resource 'https://jcenter.bintray.com/com/nhaarman/mockitokotlin2/mockito-kotlin/2.2.0/mockito-kotlin-2.2.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/nhaarman/mockitokotlin2/mockito-kotlin/2.2.0/mockito-kotlin-2.2.0.jar'.

What should I do in order to fix this error? Thanks.

Best Regards,
José Costa

**Comment by sphrak** [comment]
@edurocks its because [jcenter/bintray shut down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). You can still use it via jitpack tho however its not ideal -- note the package name is `com.github.*` instead of `com.nhaarman.*` since its autopublished by jitpack.. https://jitpack.io/p/nhaarman/mockito-kotlin

**Comment by TimvdLippe** [comment]
Closing per above comment.
